/*
Suppression des relations 
*/
/*
*************************************************
ATTENTION NE PAS TOUCHER AUX LIGNES SUIVANTES
ELLES PERMETTENT SOUS ORACLE DE SUPPRIMER PROPREMENT LES RELATIONS.
LES RELATIONS DYNAMIQUES SONT SUPPRIMEES EN PREMIER.


AVEC D'AUTRES SGBD UN :
DROP TABLE [IF EXISTS] table_name;
DEVRAIT SUFFIRRE.
*************************************************
*/
prompt "Suppression des relations"
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE EMPRUNT';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE CARACTERISE';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE EXEMPLAIRE';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ABONNE';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE MOT_CLEF';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE LIVRE';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

/*
*************************************************
*/


/*
Création des relations 
*/

prompt "Création des relations"

CREATE TABLE LIVRE (
	ISBN VARCHAR(15),
	TITRE VARCHAR(50) CONSTRAINT LITITRE NOT NULL, 
	SIECLE NUMERIC(2,0) CHECK (SIECLE BETWEEN 0 and 21),
	CATEGORIE VARCHAR(16),
	CONSTRAINT LIVREPK PRIMARY KEY (ISBN));

CREATE TABLE ABONNE (
	NUM_AB  NUMERIC(6,0),  
	NOM VARCHAR(15)  CONSTRAINT ABNOM NOT NULL, 
	PRENOM VARCHAR(20), 
	VILLE VARCHAR(13), 
	AGE NUMERIC(3,0)  ,
 	TARIF NUMERIC(3,0) ,
 	REDUC NUMERIC(3,0) ,
	CONSTRAINT DOM_AGE CHECK (AGE BETWEEN 0 AND 120),
	CONSTRAINT ABONNEPK PRIMARY KEY (NUM_AB));

CREATE TABLE EXEMPLAIRE (
	NUMERO NUMERIC(4,0), 
	DATE_ACHAT DATE, 
	PRIX NUMERIC(5,2), 
	CODE_PRET VARCHAR(20) ,
	ETAT VARCHAR(15) CHECK (ETAT IN ('BON','ABIME','EN_REPARATION')), 
	ISBN  VARCHAR(15), 
	CONSTRAINT DOM_CODE_PRET CHECK (CODE_PRET IN ('EXCLU','EMPRUNTABLE','CONSULTABLE')),
	CONSTRAINT EXEMPLAIREPK PRIMARY KEY (NUMERO), 
	CONSTRAINT EXEMPLAIREFK FOREIGN KEY (ISBN) REFERENCES LIVRE(ISBN)
);

CREATE TABLE MOT_CLEF (
	MOT VARCHAR(16),
	CONSTRAINT MOT_CLEFPK PRIMARY KEY(MOT)
);

CREATE TABLE EMPRUNT (
	NUM_AB  NUMERIC(6,0) REFERENCES ABONNE(NUM_AB),
	NUM_EX NUMERIC (4,0) REFERENCES EXEMPLAIRE(NUMERO),
	D_EMPRUNT DATE, 
	D_RETOUR DATE, 
	D_RET_REEL DATE, 
	NB_RELANCE NUMERIC(1,0) CHECK (NB_RELANCE IN (1,2,3)),
	CONSTRAINT EMPRUNTPK PRIMARY KEY (NUM_AB,NUM_EX,D_EMPRUNT)
);

CREATE TABLE CARACTERISE (
	ISBN VARCHAR(20) REFERENCES LIVRE(ISBN), 
	MOT VARCHAR(20) REFERENCES MOT_CLEF(MOT),
	CONSTRAINT CARACTERISEPK PRIMARY KEY(ISBN,MOT)
);

